const questionsEnglish = [
  // ══════════════ Grade 1 ══════════════
  // easy
  {grade:1,level:'easy',q:"What color is the sky?",c:["red","green","blue","yellow"],a:2},
  {grade:1,level:'easy',q:"How many days are in a week?",c:["5","6","7","8"],a:2},
  {grade:1,level:'easy',q:"Which animal says 'Moo'?",c:["dog","cat","cow","sheep"],a:2},
  {grade:1,level:'easy',q:"What is the opposite of 'big'?",c:["tall","small","heavy","fast"],a:1},
  {grade:1,level:'easy',q:"Which letter comes after 'A'?",c:["C","B","D","E"],a:1},
  {grade:1,level:'easy',q:"What color is grass?",c:["blue","red","green","white"],a:2},
  {grade:1,level:'easy',q:"How many legs does a dog have?",c:["2","3","4","6"],a:2},
  {grade:1,level:'easy',q:"Which is a fruit?",c:["carrot","potato","apple","onion"],a:2},
  {grade:1,level:'easy',q:"What do we use to write?",c:["spoon","pen","ruler","scissors"],a:1},
  {grade:1,level:'easy',q:"What number comes after 9?",c:["8","10","11","12"],a:1},
  // medium
  {grade:1,level:'medium',q:"Which word is a verb?",c:["house","run","big","cat"],a:1},
  {grade:1,level:'medium',q:"Complete: 'I ___ to school every day.'",c:["goes","going","go","gone"],a:2},
  {grade:1,level:'medium',q:"Which sentence is correct?",c:["He go to school","She is happy","They was playing","I are running"],a:1},
  {grade:1,level:'medium',q:"What is the plural of 'book'?",c:["bookes","bookies","books","bookes"],a:2},
  {grade:1,level:'medium',q:"Which word means the opposite of 'hot'?",c:["warm","cool","cold","mild"],a:2},
  {grade:1,level:'medium',q:"Which animal lives in water?",c:["lion","eagle","fish","elephant"],a:2},
  {grade:1,level:'medium',q:"What season comes after winter?",c:["autumn","summer","spring","fall"],a:2},
  {grade:1,level:'medium',q:"Which word is an adjective?",c:["run","beautiful","house","eat"],a:1},
  {grade:1,level:'medium',q:"Complete: 'The dog ___ the bone.'",c:["eat","eats","eating","eaten"],a:1},
  {grade:1,level:'medium',q:"How many vowels are in the English alphabet?",c:["4","5","6","7"],a:1},
  // hard
  {grade:1,level:'hard',q:"Which sentence uses the correct article?",c:["I saw a elephant","She has a apple","He is an honest man","They found a umbrella"],a:2},
  {grade:1,level:'hard',q:"Complete: 'She ___ a book yesterday.'",c:["read","reads","reading","readed"],a:0},
  {grade:1,level:'hard',q:"Which is the correct possessive form?",c:["the dog's bone","the dogs's bone","the dogs bone","the dog bone"],a:0},
  {grade:1,level:'hard',q:"What is the past tense of 'go'?",c:["goed","gone","went","goes"],a:2},
  {grade:1,level:'hard',q:"Which sentence has a mistake?",c:["They are playing","She is happy","He have a car","I am a student"],a:2},
  {grade:1,level:'hard',q:"What is the plural of 'child'?",c:["childs","children","childrens","child"],a:1},
  {grade:1,level:'hard',q:"Complete: 'Neither John nor Mary ___ ready.'",c:["are","were","is","be"],a:2},
  {grade:1,level:'hard',q:"What is the comparative of 'good'?",c:["gooder","more good","better","best"],a:2},
  {grade:1,level:'hard',q:"Identify the subject: 'The tall man opened the door.'",c:["tall","man","The tall man","opened"],a:2},
  {grade:1,level:'hard',q:"Which word is a conjunction?",c:["quickly","beautiful","and","slowly"],a:2},

  // ══════════════ Grade 2 ══════════════
  // easy
  {grade:2,level:'easy',q:"What is the capital of England?",c:["Paris","Berlin","Madrid","London"],a:3},
  {grade:2,level:'easy',q:"Which animal is the largest land animal?",c:["lion","elephant","giraffe","hippo"],a:1},
  {grade:2,level:'easy',q:"What does 'happy' mean?",c:["sad","angry","joyful","tired"],a:2},
  {grade:2,level:'easy',q:"Which is a body part?",c:["house","school","heart","street"],a:2},
  {grade:2,level:'easy',q:"What is 3 + 4 in English?",c:["six","seven","eight","nine"],a:1},
  {grade:2,level:'easy',q:"Which word rhymes with 'cat'?",c:["dog","car","bat","cup"],a:2},
  {grade:2,level:'easy',q:"What do you wear on your feet?",c:["hat","gloves","shoes","scarf"],a:2},
  {grade:2,level:'easy',q:"Which month comes after January?",c:["March","April","February","June"],a:2},
  {grade:2,level:'easy',q:"What is the opposite of 'day'?",c:["morning","evening","night","noon"],a:2},
  {grade:2,level:'easy',q:"Which is a vegetable?",c:["apple","mango","carrot","peach"],a:2},
  // medium
  {grade:2,level:'medium',q:"Which tense is used in: 'He is eating now'?",c:["simple present","present continuous","past tense","future tense"],a:1},
  {grade:2,level:'medium',q:"What is the past tense of 'run'?",c:["runned","runs","ran","running"],a:2},
  {grade:2,level:'medium',q:"Complete: 'They ___ football yesterday.'",c:["play","plays","playing","played"],a:3},
  {grade:2,level:'medium',q:"Which is an adverb?",c:["quick","quickly","quicker","quickest"],a:1},
  {grade:2,level:'medium',q:"What is the plural of 'mouse'?",c:["mouses","mooses","mice","mices"],a:2},
  {grade:2,level:'medium',q:"Which sentence is in the future tense?",c:["She runs fast","She ran fast","She will run fast","She is running"],a:2},
  {grade:2,level:'medium',q:"What type of word is 'London'?",c:["common noun","verb","proper noun","adjective"],a:2},
  {grade:2,level:'medium',q:"Complete: 'I have ___ eaten dinner.'",c:["yet","still","already","since"],a:2},
  {grade:2,level:'medium',q:"What is the superlative of 'tall'?",c:["taller","tallest","most tall","more tall"],a:1},
  {grade:2,level:'medium',q:"Which sentence uses 'too' correctly?",c:["She too is smart","The bag is too heavy","Too the bag is heavy","She is too smart too"],a:1},
  // hard
  {grade:2,level:'hard',q:"Which sentence uses the present perfect correctly?",c:["I have went to Paris","She has eaten already","They have runned fast","He have seen it"],a:1},
  {grade:2,level:'hard',q:"What does 'despite' mean?",c:["because of","in spite of","due to","as a result of"],a:1},
  {grade:2,level:'hard',q:"Complete: 'If it rains, we ___ stay home.'",c:["will","would","can","could"],a:0},
  {grade:2,level:'hard',q:"Which is passive voice?",c:["She wrote the letter","The letter was written","She is writing","They write letters"],a:1},
  {grade:2,level:'hard',q:"What is the meaning of 'eloquent'?",c:["shy","well-spoken","rude","quiet"],a:1},
  {grade:2,level:'hard',q:"Which uses 'since' correctly?",c:["I have known him since 2010","I knew him since long","She was here since yesterday","They come since Monday"],a:0},
  {grade:2,level:'hard',q:"Complete: 'The book, ___ I borrowed, was excellent.'",c:["who","whom","that","which"],a:3},
  {grade:2,level:'hard',q:"What is the synonym of 'enormous'?",c:["tiny","huge","narrow","weak"],a:1},
  {grade:2,level:'hard',q:"Which sentence has a dangling modifier?",c:["Walking to school, I saw a bird.","Walking to school, the bird was seen.","The bird was seen while I walked.","I walked and saw a bird."],a:1},
  {grade:2,level:'hard',q:"What is the antonym of 'benevolent'?",c:["kind","generous","malevolent","gentle"],a:2},

  // ══════════════ Grade 3 ══════════════
  // easy
  {grade:3,level:'easy',q:"Which word means 'to feel sorry for someone'?",c:["envy","sympathy","jealousy","pride"],a:1},
  {grade:3,level:'easy',q:"What is the past participle of 'write'?",c:["wrote","writen","written","writing"],a:2},
  {grade:3,level:'easy',q:"Which sentence is grammatically correct?",c:["She don't like coffee","He doesn't like coffee","They doesn't like coffee","I doesn't like it"],a:1},
  {grade:3,level:'easy',q:"What type of sentence is: 'Close the door!'?",c:["declarative","interrogative","imperative","exclamatory"],a:2},
  {grade:3,level:'easy',q:"Complete: 'She sang ___ well that everyone clapped.'",c:["so","such","very","too"],a:0},
  {grade:3,level:'easy',q:"What does 'exhausted' mean?",c:["excited","very tired","very angry","bored"],a:1},
  {grade:3,level:'easy',q:"Which is a preposition?",c:["quickly","beautiful","under","running"],a:2},
  {grade:3,level:'easy',q:"What is the noun form of 'decide'?",c:["deciding","decisive","decision","decided"],a:2},
  {grade:3,level:'easy',q:"Complete: 'He asked me ___ I was feeling well.'",c:["that","if","when","what"],a:1},
  {grade:3,level:'easy',q:"What is the adjective form of 'courage'?",c:["courageous","courageously","couraging","encourage"],a:0},
  // medium
  {grade:3,level:'medium',q:"Which sentence uses reported speech correctly?",c:["She said she is happy","She said she was happy","She said she were happy","She said she be happy"],a:1},
  {grade:3,level:'medium',q:"What does the prefix 'un-' mean?",c:["again","before","not","under"],a:2},
  {grade:3,level:'medium',q:"Which is a conditional sentence?",c:["She is running.","If you study, you will pass.","He ran fast.","Open the window."],a:1},
  {grade:3,level:'medium',q:"What is the difference between 'affect' and 'effect'?",c:["same meaning","affect is a verb, effect is a noun","effect is a verb, affect is a noun","both are adjectives"],a:1},
  {grade:3,level:'medium',q:"Complete: 'She ___ here for three years.'",c:["has been","was been","have been","been"],a:0},
  {grade:3,level:'medium',q:"What is a metaphor?",c:["A direct comparison using 'like' or 'as'","An indirect comparison saying something IS something else","A type of rhyme","A figure of repetition"],a:1},
  {grade:3,level:'medium',q:"Which is an example of alliteration?",c:["The cat sat.","Peter Piper picked peppers.","She is beautiful.","He ran fast."],a:1},
  {grade:3,level:'medium',q:"Complete: 'By the time she arrived, he ___ already left.'",c:["had","has","have","did"],a:0},
  {grade:3,level:'medium',q:"What is the meaning of 'ambiguous'?",c:["clear and obvious","having more than one meaning","very difficult","completely wrong"],a:1},
  {grade:3,level:'medium',q:"Which word correctly completes: 'Neither of them ___ right.'",c:["are","were","is","be"],a:2},
  // hard
  {grade:3,level:'hard',q:"What is the subjunctive mood used for?",c:["stating facts","expressing wishes, hypotheticals, or doubts","asking questions","giving commands"],a:1},
  {grade:3,level:'hard',q:"Complete: 'I wish I ___ taller.'",c:["am","was","were","be"],a:2},
  {grade:3,level:'hard',q:"What is a gerund?",c:["a verb in the past tense","a verb used as a noun (ending in -ing)","an adjective describing action","an adverb"],a:1},
  {grade:3,level:'hard',q:"Which sentence has an error?",c:["She suggested going early.","He denied having stolen it.","They agreed to cooperate.","She recommended to leave now."],a:3},
  {grade:3,level:'hard',q:"What does 'plethora' mean?",c:["shortage","a very large amount","a specific type","uncertainty"],a:1},
  {grade:3,level:'hard',q:"Complete the idiom: 'Bite the ___'",c:["apple","dust","hand","bullet"],a:3},
  {grade:3,level:'hard',q:"Which is an example of irony?",c:["'Run fast!'","'A fire station burns down.'","'The sky is blue.'","'She smiled.'"],a:1},
  {grade:3,level:'hard',q:"What is the literary term for attributing human qualities to non-human things?",c:["simile","metaphor","personification","hyperbole"],a:2},
  {grade:3,level:'hard',q:"Complete: 'Had I known, I ___ come.'",c:["will","would have","would","had"],a:1},
  {grade:3,level:'hard',q:"What is the tone of a text?",c:["the literal meaning","the author's attitude toward the subject","the main theme","the plot structure"],a:1},

  // ══════════════ Grade 4 ══════════════
  // easy
  {grade:4,level:'easy',q:"What is a thesis statement?",c:["a topic sentence","the main argument of an essay","a conclusion","a quotation"],a:1},
  {grade:4,level:'easy',q:"Which sentence uses 'fewer' correctly?",c:["I have less apples","I have fewer apples","I have lesser apples","I have a few less apples"],a:1},
  {grade:4,level:'easy',q:"What is the meaning of 'vague'?",c:["very clear","precise","not clear or exact","very long"],a:2},
  {grade:4,level:'easy',q:"Which is a complex sentence?",c:["He ran and jumped.","She sings.","Although it rained, we played outside.","Run fast!"],a:2},
  {grade:4,level:'easy',q:"What does 'contradict' mean?",c:["to agree","to support","to say the opposite","to explain"],a:2},
  {grade:4,level:'easy',q:"What is the adverb in: 'He speaks very quietly.'?",c:["speaks","very quietly","very","quietly"],a:3},
  {grade:4,level:'easy',q:"Which is a compound word?",c:["running","beautiful","sunflower","quickly"],a:2},
  {grade:4,level:'easy',q:"What is the meaning of 'persevere'?",c:["to give up","to continue despite difficulties","to rest","to argue"],a:1},
  {grade:4,level:'easy',q:"Complete: 'I am interested ___ learning English.'",c:["to","at","in","on"],a:2},
  {grade:4,level:'easy',q:"What type of word is 'however'?",c:["conjunction","preposition","conjunctive adverb","article"],a:2},
  // medium
  {grade:4,level:'medium',q:"What is the purpose of a topic sentence?",c:["to end a paragraph","to introduce the main idea of a paragraph","to provide evidence","to add details"],a:1},
  {grade:4,level:'medium',q:"What is the difference between 'principle' and 'principal'?",c:["same meaning","principle is a rule, principal is head/main","principal is a rule, principle is head","both mean rules"],a:1},
  {grade:4,level:'medium',q:"Complete: '___ you finish, please turn off the lights.'",c:["After","Because","Although","However"],a:0},
  {grade:4,level:'medium',q:"What is parallelism in writing?",c:["using metaphors","using the same grammatical structure in a series","repeating words","avoiding repetition"],a:1},
  {grade:4,level:'medium',q:"Which sentence has correct subject-verb agreement?",c:["The team are playing well.","The team is playing well.","The teams is playing.","The team plays well all of them."],a:1},
  {grade:4,level:'medium',q:"What does 'allusion' mean?",c:["an illusion","a brief indirect reference to something","a direct quote","a contradiction"],a:1},
  {grade:4,level:'medium',q:"Which is an example of a euphemism?",c:["He is dead.","He has passed away.","He was killed.","He stopped living."],a:1},
  {grade:4,level:'medium',q:"What is the function of a semicolon?",c:["to end a sentence","to introduce a list","to join two related independent clauses","to show possession"],a:2},
  {grade:4,level:'medium',q:"What is 'diction' in writing?",c:["punctuation use","word choice","sentence length","text structure"],a:1},
  {grade:4,level:'medium',q:"Which word correctly completes: 'She is ___ her sister.'",c:["tall as","as tall as","taller to","as taller than"],a:1},
  // hard
  {grade:4,level:'hard',q:"What is the difference between 'imply' and 'infer'?",c:["same meaning","the speaker implies, the listener infers","the listener implies, the speaker infers","both mean to suggest"],a:1},
  {grade:4,level:'hard',q:"What is a 'foil' character in literature?",c:["the main character","a character who contrasts with the protagonist","a narrator","a villain"],a:1},
  {grade:4,level:'hard',q:"What is the literary term for extreme exaggeration?",c:["metaphor","irony","hyperbole","alliteration"],a:2},
  {grade:4,level:'hard',q:"Complete: 'She demanded that he ___ the truth.'",c:["tells","told","tell","would tell"],a:2},
  {grade:4,level:'hard',q:"What is 'stream of consciousness' in literature?",c:["a type of plot","a narrative technique showing unfiltered thoughts","dialogue between characters","a genre of poetry"],a:1},
  {grade:4,level:'hard',q:"Which correctly uses an em dash?",c:["She said—he was wrong","She was—right","The answer—was obvious—surprised us all.","She—ran fast"],a:2},
  {grade:4,level:'hard',q:"What is the meaning of 'ephemeral'?",c:["lasting forever","lasting a very short time","extremely large","very important"],a:1},
  {grade:4,level:'hard',q:"What is the term for a story within a story?",c:["flashback","subplot","frame narrative","epilogue"],a:2},
  {grade:4,level:'hard',q:"Which sentence uses the inversion correctly?",c:["Never I have seen this.","Never have I seen this.","I never have seen this.","Have never I seen this."],a:1},
  {grade:4,level:'hard',q:"What is the difference between 'denotation' and 'connotation'?",c:["same meaning","denotation is literal meaning, connotation is associated meaning","connotation is literal, denotation is associated","both are figurative"],a:1},

  // ══════════════ Grade 5 ══════════════
  // easy
  {grade:5,level:'easy',q:"What is the meaning of 'prolific'?",c:["lazy","producing a lot","rare","small"],a:1},
  {grade:5,level:'easy',q:"Which is correct: 'He is ___ than his brother.'",c:["more taller","tallest","taller","most tall"],a:2},
  {grade:5,level:'easy',q:"What is a rhetorical question?",c:["a question without a question mark","a question asked for effect, not a real answer","a very long question","a yes/no question"],a:1},
  {grade:5,level:'easy',q:"What does 'explicit' mean?",c:["hidden","unclear","clearly stated","implied"],a:2},
  {grade:5,level:'easy',q:"Which sentence is in the passive voice?",c:["She wrote the report.","The report was written by her.","She is writing the report.","She will write the report."],a:1},
  {grade:5,level:'easy',q:"What is a 'motif' in literature?",c:["the main character","a recurring element with symbolic significance","the setting","the conclusion"],a:1},
  {grade:5,level:'easy',q:"What does the suffix '-ology' mean?",c:["against","the study of","before","full of"],a:1},
  {grade:5,level:'easy',q:"Complete: 'It's time you ___ your homework.'",c:["do","did","done","doing"],a:1},
  {grade:5,level:'easy',q:"What is an oxymoron?",c:["a figure of exaggeration","a figure combining contradictory terms (e.g., 'deafening silence')","a type of rhyme","a metaphor"],a:1},
  {grade:5,level:'easy',q:"Which is a dependent clause?",c:["She ran fast.","He is tall.","Although it was raining","Open the window."],a:2},
  // medium
  {grade:5,level:'medium',q:"What is the term for the turning point in a narrative?",c:["exposition","resolution","climax","falling action"],a:2},
  {grade:5,level:'medium',q:"Which correctly uses a colon?",c:["She has one goal: to succeed.","She has one: goal to succeed.","One goal to: succeed.","She: has one goal to succeed."],a:0},
  {grade:5,level:'medium',q:"What is the function of 'nevertheless' in a sentence?",c:["to add information","to show contrast despite the previous point","to explain cause","to give an example"],a:1},
  {grade:5,level:'medium',q:"Which is an example of understatement?",c:["It was a catastrophe!","It was the end of the world.","It was a bit of a problem.","It was absolutely terrible."],a:2},
  {grade:5,level:'medium',q:"What is a 'round' character in fiction?",c:["a character who never changes","a complex, multi-dimensional character","the antagonist","the narrator"],a:1},
  {grade:5,level:'medium',q:"What does 'juxtaposition' mean?",c:["repetition of sounds","placing contrasting elements side by side","using metaphors","the story's conflict"],a:1},
  {grade:5,level:'medium',q:"Which sentence uses 'whom' correctly?",c:["To who did you give it?","Whom is calling?","To whom did you give it?","Whom is the winner?"],a:2},
  {grade:5,level:'medium',q:"What is 'syntax' in linguistics?",c:["word meaning","word formation","sentence structure","pronunciation"],a:2},
  {grade:5,level:'medium',q:"What does 'didactic' mean?",c:["entertaining","designed to teach a moral lesson","humorous","dramatic"],a:1},
  {grade:5,level:'medium',q:"Complete: 'She acts as though she ___ everything.'",c:["know","knows","knew","known"],a:2},
  // hard
  {grade:5,level:'hard',q:"What is the difference between 'Romantic' and 'romantic'?",c:["no difference","Romantic refers to the literary period, romantic to love","romantic refers to the period, Romantic to love","both refer to love"],a:1},
  {grade:5,level:'hard',q:"What is a 'Bildungsroman'?",c:["a German short story","a coming-of-age novel","a type of poem","a narrative technique"],a:1},
  {grade:5,level:'hard',q:"Which correctly uses the Oxford comma?",c:["I ate eggs, bacon and toast","I ate eggs, bacon, and toast","I ate eggs bacon and toast","I ate, eggs, bacon, and toast"],a:1},
  {grade:5,level:'hard',q:"What is 'polysyndeton'?",c:["using too few conjunctions","using many conjunctions for effect","a type of rhyme","parallel structure"],a:1},
  {grade:5,level:'hard',q:"What is the literary term for a hint of future events?",c:["flashback","climax","foreshadowing","epilogue"],a:2},
  {grade:5,level:'hard',q:"Complete: 'No sooner ___ he arrived than it started raining.'",c:["did","had","has","was"],a:1},
  {grade:5,level:'hard',q:"What does 'equivocal' mean?",c:["clear and direct","having two or more possible meanings","absolutely wrong","very obvious"],a:1},
  {grade:5,level:'hard',q:"What is 'pathos' in rhetoric?",c:["appeal to logic","appeal to ethics/credibility","appeal to emotion","appeal to authority"],a:2},
  {grade:5,level:'hard',q:"What is the term for a story's time and place setting?",c:["plot","theme","setting","tone"],a:2},
  {grade:5,level:'hard',q:"Which sentence correctly uses a nominative absolute?",c:["She ran fast.","The work finished, she went home.","Having finished, she was happy.","She finished and went home."],a:1},

  // ══════════════ Grade 6 ══════════════
  // easy
  {grade:6,level:'easy',q:"What is 'ethos' in rhetoric?",c:["appeal to emotion","appeal to credibility/ethics","appeal to logic","appeal to beauty"],a:1},
  {grade:6,level:'easy',q:"What is 'logos' in rhetoric?",c:["appeal to emotion","appeal to ethics","appeal to logic/reason","appeal to nature"],a:2},
  {grade:6,level:'easy',q:"What is a 'soliloquy'?",c:["a dialogue between two characters","a speech made to oneself revealing inner thoughts","a type of poem","a concluding chapter"],a:1},
  {grade:6,level:'easy',q:"What is the meaning of 'pragmatic'?",c:["idealistic","practical and realistic","theoretical","emotional"],a:1},
  {grade:6,level:'easy',q:"Which is an example of onomatopoeia?",c:["quickly","beautiful","buzz","lovely"],a:2},
  {grade:6,level:'easy',q:"What is a 'denouement'?",c:["the rising action","the climax","the resolution/outcome of a story","the introduction"],a:2},
  {grade:6,level:'easy',q:"What does 'ubiquitous' mean?",c:["rare","found everywhere","very large","ancient"],a:1},
  {grade:6,level:'easy',q:"Which is an example of synecdoche?",c:["'He is a lion in battle.'","'All hands on deck.'","'The wind whispered.'","'She is as fast as lightning.'"],a:1},
  {grade:6,level:'easy',q:"What is the meaning of 'sardonic'?",c:["kind and generous","grimly mocking or cynical","extremely happy","very confused"],a:1},
  {grade:6,level:'easy',q:"What is an 'unreliable narrator'?",c:["a narrator who speaks too quietly","a narrator whose credibility is compromised","a third-person narrator","an omniscient narrator"],a:1},
  // medium
  {grade:6,level:'medium',q:"What is the difference between 'theme' and 'subject'?",c:["no difference","subject is the topic, theme is the message/insight about the topic","theme is the topic, subject is the message","both are the same as plot"],a:1},
  {grade:6,level:'medium',q:"What is 'epistrophe' as a rhetorical device?",c:["repetition at the beginning of clauses","repetition at the end of successive clauses","a type of metaphor","using understatement"],a:1},
  {grade:6,level:'medium',q:"Complete: 'Were I in your position, I ___ accept the offer.'",c:["will","would","shall","should"],a:1},
  {grade:6,level:'medium',q:"What is the term for the attitude of a work toward its audience?",c:["theme","tone","mood","diction"],a:1},
  {grade:6,level:'medium',q:"What does 'verisimilitude' mean?",c:["absolute truth","the appearance of being true or real","complete fiction","historical accuracy"],a:1},
  {grade:6,level:'medium',q:"What is 'anachronism' in literature?",c:["a type of narrator","placing something in the wrong time period","a circular plot","a type of irony"],a:1},
  {grade:6,level:'medium',q:"Which correctly uses the past perfect passive?",c:["The book was written.","The book had been written.","The book has been written.","The book were written."],a:1},
  {grade:6,level:'medium',q:"What is a 'dynamic' character?",c:["a very energetic character","a character who undergoes significant change","the main character","a character with many traits"],a:1},
  {grade:6,level:'medium',q:"What is 'deus ex machina'?",c:["a type of setting","an unlikely resolution that suddenly solves the conflict","a recurring symbol","a narrative technique"],a:1},
  {grade:6,level:'medium',q:"Which is an example of chiasmus?",c:["'Ask not what your country can do for you—ask what you can do for your country.'","'I came, I saw, I conquered.'","'To be or not to be.'","'Veni, vidi, vici.'"],a:0},
  // hard
  {grade:6,level:'hard',q:"What is 'polyphony' in the context of the novel?",c:["use of multiple languages","multiple independent voices and perspectives","a musical metaphor","a narrative technique"],a:1},
  {grade:6,level:'hard',q:"What is the difference between 'mimesis' and 'diegesis'?",c:["no difference","mimesis shows/enacts, diegesis tells/reports","diegesis shows, mimesis tells","both mean narration"],a:1},
  {grade:6,level:'hard',q:"Complete: 'Little ___ she know what awaited her.'",c:["did","does","had","was"],a:0},
  {grade:6,level:'hard',q:"What is 'apophasis'?",c:["a type of metaphor","mentioning something by saying you will not mention it","a type of paradox","extreme understatement"],a:1},
  {grade:6,level:'hard',q:"What is the concept of 'defamiliarization' in literary theory?",c:["using familiar language","making the familiar seem strange to give new perspective","analyzing grammar","avoiding metaphors"],a:1},
  {grade:6,level:'hard',q:"Which sentence uses inversion for emphasis correctly?",c:["Rarely do we see such talent.","We rarely do see such talent.","Such talent rarely we see.","We do rarely see such talent."],a:0},
  {grade:6,level:'hard',q:"What does 'aporia' mean in rhetoric?",c:["excessive confidence","expressing genuine or feigned doubt","a type of conclusion","logical proof"],a:1},
  {grade:6,level:'hard',q:"What is the 'hermeneutic circle'?",c:["a type of narrative structure","the interpretive process where understanding parts requires the whole and vice versa","a logical fallacy","a poetic form"],a:1},
  {grade:6,level:'hard',q:"What is the difference between 'anaphora' and 'epistrophe'?",c:["no difference","anaphora repeats at the beginning, epistrophe at the end","epistrophe repeats at the beginning, anaphora at the end","both are types of rhyme"],a:1},
  {grade:6,level:'hard',q:"What is 'free indirect discourse'?",c:["direct speech without quotation marks","a narrative technique blending narrator and character voices","first-person narration","a type of stream of consciousness"],a:1}
];
